# Generated by Django 4.1 on 2022-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=3000)),
                ('app_url', models.CharField(max_length=2000)),
                ('date_app', models.CharField(max_length=100)),
            ],
        ),
    ]
